directories:
  output: "D:\\manim-media\\videos"
  raster_images: "D:\\manim-media\\images\\raster"
  vector_images: "D:\\manim-media\\images\\vector"
  sounds: "D:\\manim-media\\sounds"
  temporary_storage: "D:\\manim-media\\cache"
  data: "D:\\manim-media\\data"

style:
  font: "Georgia"
  background_color: "#111111"

camera_qualities:
  default_quality: "ultra_high"
